---
- name: TEST PLAYBOOK FOR ARISTA
  hosts: EOS1
  connection: network_cli
  gather_facts: no

  tasks:
    - name: COLLECTION INFOR FROM ROUTER
      ios_command:
        commands:
          - show version
          - show hostname

      register: show_commands

    - name: CREATING VARS
      set_fact:
        sw_version: "{{ show_commands.stdout_lines[0][5].split(':')[1] }}"

    - name: VALIDATION OUTPUT
      debug:
        msg: "{{ sw_version }}"
...
