#!/usr/bin//env python

# Modules

import json


# Variables

path_inventory = 'Inventory/inventory.json'


# User defines functon

def JSONtoDICT(filepath):
    f = open(filepath, 'r')
    new_dict = json.loads(f.open())
    f.close()

    return new_dict


# Body

inventory = JSONtoDICT(path_inventory)
print(inventory)
